#/vis/open OGLIX 800x800
/vis/open DAWNFILE
/vis/viewer/set/upVector 1 0 0 
/vis/viewer/set/viewpointThetaPhi 90 90 
/tracking/storeTrajectory 1
#/vis/filtering/trajectories/create/chargeFilter
#/vis/filtering/trajectories/chargeFilter-0/add +1
#/vis/filtering/trajectories/chargeFilter-0/verbose true
#/vis/filtering/trajectories/chargeFilter-0/reset true
/vis/drawVolume
/vis/scene/add/trajectories
/vis/scene/add/axes 0 0 0 50 cm
/vis/scene/endOfEventAction accumulate 100
/vis/scene/endOfRunAction accumulate
/vis/viewer/flush
#/lamps/useEventFile 1
#/lamps/eventFileNum 0
#/run/verbose 1
#/event/verbose 1
#/tracking/verbose 1
#/run/beamOn 1
